# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  srpm-to-build:  # id of input
    description: 'the SRPM file to use for building RPMS'
    required: false
    default: '/srpm/icinga2-2.13.5-1.fc36.icinga.src.rpm'
  source_rpm: 
    default: 'icinga2-2.13.5-1.fc36.icinga.src.rpm'
    required: false
  mock_config: 
    default: 'rocky+epel-9-x86_64'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    SOURCE_RPM: ${{ inputs.srpm-to-build }}
    MOCK_CONFIG: ${{ inputs.mock_config }}
  #with:
  #  options: --privileged

  args:
    - --privileged
  #  - SOURCE_RPM=${{ inputs.srpm-to-build }}
  #  - MOCK_CONFIG=${{ inputs.mock_config }}
