# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  srpm-to-build:  # id of input
    description: 'the SRPM file to use for building RPMS'
    required: true
    default: 'icinga2-2.13.5-1.fc36.icinga.src.rpm'
  SOURCE_RPM: 
    default: 'icinga2-2.13.5-1.fc36.icinga.src.rpm'
  MOCK_CONFIG: 
    default: 'rocky+epel-9-x86_64'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.srpm-to-build }}
    - ${{ inputs.SOURCE_RPM }}
    - ${{ inputs.MOCK_CONFIG }}
