on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: docker.io/vgerris/mock-rpmbuilder
      env:
        ASAN_OPTIONS: detect_leaks=0
      options: --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged
    name: A job to build RPM files
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Run rpm build command
        id: hello
        run: |
          pwd && ls -lrta
          echo $SOURCE_RPM
          export SOURCE_RPM="/srpm/icinga2-2.13.5-1.fc36.icinga.src.rpm"
          export MOCK_CONFIG="rocky+epel-9-x86_64"
          /build-rpm.sh 
        # with:
          #entrypoint: /build-rpm.sh
          #args: --privileged --security-opt seccomp=unconfined
          #options: --privileged
        #with:
        #  entryPoint: '/build-rpm.sh'
        env: 
          SOURCE_RPM: /srpm/icinga2-2.13.5-1.fc36.icinga.src.rpm
          MOCK_CONFIG: rocky+epel-9-x86_64
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            /output/rocky+epel-9-x86_64

